python build_commonvoice_22_webdataset.py \
  --commonvoice-dir $1 \
  --output-dir $2 \
  --tokenizer $3 \
  --mimi-ckpt $4 \
  --task mixed \
  --asr-ratio 0.5 \
  --num-codebooks $5 \
  --num-workers $6 \
  --worker-id $7 \
  --split $8 \
  --maxcount 10000
